<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerT405BKZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT405BKZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerT405BKZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerT405BKZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerT405BKZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'T405BKZ',
    'container.build_id' => 'a09fa14c',
    'container.build_time' => 1777305277,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerT405BKZ');
